change normalizedQuotes to use a temp var instead a full search for t…
codeofsumit/tresor-returns pull request #6
Opened 2020-10-27 19:04 UTC by rubensstarke

hey guys, i changed normalizedQuotes to use a temp var instead a full search for the prev price and with just one iteration, i got a good result in benchmark.

Explanation: when a quote have the price i save it in **prev** var, on the next item if it dont have a price a set it to the **prev** saved price.

Benchmark:
![Captura de Tela 2020-10-27 às 14 58 33](https://user-images.githubusercontent.com/4966360/97348703-4a2e9200-186d-11eb-8090-b820dc70a499.png)

![image](https://user-images.githubusercontent.com/4966360/97349321-1acc5500-186e-11eb-8677-9bd11e374182.png)

2020-10-27 21:10 UTC, codeofsumit reviewed
Looks nice and much cleaner 👏.
How do you handle the case when the first positions in the array don't have a quote? E.g. first 10 positions are empty and the first quote is found at 11. How do you fill the first 10 positions (with the 11th quote)?

2020-10-27 21:10 UTC, felix-adnymics commented
LGTM, just for readability reasons:
can't we simply return `prevprice` as `price`? The condition's checked earlier already.

(+ I'd love to stick to lower camel case --> `prevPrice`)

2020-10-27 21:16 UTC, felixheck commented
what he says ☝️😁

2020-10-27 21:32 UTC, felixheck commented on utils.js
> +      price: q && q.price ? q.price : prevprice
Has already been checked in `L56-57`, thus it can be `price: prevprice`

2020-10-27 21:32 UTC, felixheck commented on utils.js
> +  let prevprice = 0
lowerCamelCase plz 🙏 😊

2020-10-27 21:32 UTC, felixheck commented on utils.js
> -      q.price = getPreviousValue(
lookahead's missing. see comment of Sumit

2020-10-27 22:11 UTC, rubensstarke commented on utils.js
> -      q.price = getPreviousValue(
in this example of Sumit the value should be the 11th position instead of zero?

2020-10-27 22:12 UTC, rubensstarke commented on utils.js
> +  let prevprice = 0
sorry i will change to `price`, more readable :)

2020-10-27 22:18 UTC, codeofsumit commented on utils.js
> -      q.price = getPreviousValue(
In case of the first elements of the array are missing a price, the first available price should be filled in to the first missing indexes.

Example:

quotes: [null, null, 5, 3, null, 4, 2, 3]
normalize()
result: [5, 5, 5, 3, 3, 4, 2, 3]

Makes sense?

2020-10-27 23:08 UTC, rubensstarke commented on utils.js
> -      q.price = getPreviousValue(
make sense! i forgot this are quotes, not activities haha

2020-10-27 23:24 UTC, rubensstarke commented
@felixheck @codeofsumit 
how about using a for, save in a temporary var which index is null if you haven't found a price yet

```javascript
function normalizeQuotes (quotes = [], dates) {
  let price = 0

  const quotesPerDay = []
  let needToFill = []
  let alreadyFindPrice = false

  for (let i = 0; i < dates.length; i++) {
    const t = dates[i]

    // TODO: possible perf potential
    const q = find(quotes, x => x.date === t)

    if (q && q.price) {
      price = q.price

      // if is the first time we have a price we will fill the empty firsts before continue
      if (!alreadyFindPrice) {
        needToFill.map(n => quotesPerDay[n].price = price)
        needToFill.length = 0
        alreadyFindPrice = true
      }

    // if the firsts are null and the alreadyFindPrice is false
    } else if (!alreadyFindPrice) {
      needToFill.push(i)
    }

    quotesPerDay.push({
      date: t,
      price
    })
  }

  return quotesPerDay
}
```

The benchmark for this function is:
![image](https://user-images.githubusercontent.com/4966360/97372112-955a9c00-1891-11eb-8b0c-3496defe746c.png)

The benchmark for all script is 2400ms vs 4040ms:
![image](https://user-images.githubusercontent.com/4966360/97372238-e9fe1700-1891-11eb-8c5c-b191bd47a561.png)

The result is diferent than before because i am home, another PC :)

2020-10-28 07:06 UTC, felixheck commented on utils.js
> +  let prevprice = 0
no "sorry" needed — really appreciate your support 😊

2020-10-28 07:14 UTC, felixheck commented
@rubensstarke having a tempvar that check if a price has been found or not: makes sense.
not entirely get the `needToFill`, isn't always `quotes.slice(0, i).map...`?

2020-10-28 07:23 UTC, felixheck commented
@rubensstarke tempvar `alreadyFoundPrice` sounds good to me. Not sure about the purpose of the `needToFill` though. It is always `quotes.slice(0, i).map...` isn't it?

2020-10-28 20:51 UTC, rubensstarke commented
@felixheck i will compare the two ways and back here soon

2020-10-28 22:38 UTC, rubensstarke commented
With a map like @felixheck suggested
![with for](https://user-images.githubusercontent.com/4966360/97504075-fb5c2780-1954-11eb-90bc-ee73886c11c1.png)

2020-10-29 08:38 UTC, felixheck commented
love it! ❤️

2020-10-29 08:39 UTC, felixheck approved these changes

2020-10-29 21:07 UTC, codeofsumit requested changes
Promising. Really looking forward having these changes merged. Nice work so far! Not much left to bring it over the finish line 👌

2020-10-29 21:07 UTC, codeofsumit commented on utils.js
>  function normalizeQuotes (quotes = [], dates) {
Let's add proper documentation here on what the function does. What the expected input and output is. Other OSS users should know about the WHAT & WHY more than the HOW.

2020-10-29 21:07 UTC, codeofsumit commented on utils.js
> +      if (!alreadyFindPrice) {
I think we can choose a clearer variable name for `alreadyFindPrice`.

From my understanding, this flags if we found a price. I would propose a variable name like `priceFound`.

2020-10-29 21:07 UTC, codeofsumit commented on utils.js
> +        quotesPerDay.slice(0, i).map(q => q.price = price);
Smart, I like it 👏
Please add documentation above to explain what it does. E.g.
```
// Fills empty starting values by take the first empty elements of the array and fill in the first price that was found.
```

2020-10-29 22:45 UTC, rubensstarke commented on utils.js
>      const q = find(quotes, x => x.date === t)
using lodash like @felixheck suggests, or really change the quotes json?
i need to test if we will have perf issues with lodash.

2020-11-03 08:01 UTC, codeofsumit approved these changes
Awesome!

2020-11-04 19:17 UTC, merged